create database EXERCICIO1p0;
GO

USE EXERCICIO1p0

CREATE TABLE Genero(
idGenero INT PRIMARY KEY IDENTITY,
nomeGenero VARCHAR(200)
GO

CREATE TABLE Filme(
idFilme INT PRIMARY KEY IDENTITY,
idGenero INT FOREIGN KEY REFERENCES Genero(idGenero),
TituloFilme VARCHAR(200)
GO